import { ChatroomSortParam } from '@/types/chatTypes';

export const endpoints = {
  auth: {
    signup: '/user/register',
    login: '/auth/login',
    logout: '/auth/logout',
    deleteUser: '/user/leave',
    checkNicknameDuplicate: '/user/exists/nickname',
    checkUsernameDuplicate: '/user/exists/username',
    refreshToken: '/auth/refresh',
    getUserDetails: '/user/detail',
    getOnboardingUserDetails: '/user/oauth/profile',
    updateOnboardingUserDetails: '/user/oauth/profile',
    updateUserDetails: '/user/update',
    updatePassword: '/user/password',
    dataReset: '/user/reset',
    findUsername: '/user/username-recovery',
    verifyUser: '/user/verify-user',
    resetPassword: '/user/reset-password',
    getUserRole: '/user/role',
  },
  email: {
    getUserEmail: '/user/email',
    changeEmail: '/user/email',
    sendEmail: '/email/send',
    verifyCode: '/email/verify',
  },
  total: {
    getMonthlyTotal: (date: string) => `/transactions/monthly/total?date=${date}`,
  },
  transaction: {
    getDailyDetails: (date: string) => `/transactions/daily/details?date=${date}`,
    getIterationExpense: '/expense/iteration/details',
    getIterationIncome: '/income/iteration/details',
    addExpense: '/expense',
    getExpense: (id: string) => `/expense/${id}`,
    updateExpense: (id: string) => `/expense/${id}`,
    deleteExpense: (id: string) => `/expense/${id}`,
    addIncome: '/income',
    getIncome: (id: string) => `/income/${id}`,
    updateIncome: (id: string) => `/income/${id}`,
    deleteIncome: (id: string) => `/income/${id}`,
  },
  category: {
    updateActive: (id: string) => `/category/active/${id}`,
    getActive: (type: string) => `/category/active?type=${type}`,
    getDefaultExpense: '/category/expense/default',
    getCustomExpense: '/category/expense/custom',
    getDefaultIncome: '/category/income/default',
    getCustomIncome: '/category/income/custom',
    addExpense: '/category/expense',
    addIncome: '/category/income',
    getCategory: (id: string) => `/category/${id}`,
    updateCategory: (id: string) => `/category/${id}`,
    deleteCategory: (id: string) => `/category/${id}`,
  },
  report: {
    getYearlySummary: (date: string) => `/transactions/yearly/total?date=${date}`,
    getWeeklySummary: (date: string) => `/transactions/weekly/total?date=${date}`,
    getWeeklyDetails: (date: string, week: string, cursor: string | null) =>
      `/transactions/weekly/details?date=${date}&week=${week}${cursor ? `&cursor=${cursor}` : ''}`,
  },
  chart: {
    getExpenseTotalAndSavings: (date: string) => `/chart/expense/total?date=${date}`,
    getExpenseStackedBarChart: (date: string) => `/chart/category/expense?date=${date}`,
    getExpenseBarChart: (date: string) => `/chart/expense/bar?date=${date}`,
    getIncomeTotalAndSavings: (date: string) => `/chart/income/total?date=${date}`,
    getIncomeStackedBarChart: (date: string) => `/chart/category/income?date=${date}`,
    getIncomeBarChart: (date: string) => `/chart/income/bar?date=${date}`,
    getLineChart: (categoryId: string, date: string) => `/chart/${categoryId}/line?date=${date}`,
    getVerticalBarChart: (categoryId: string, date: string) => `/chart/${categoryId}/vertical?date=${date}`,
    getCategoryLogs: (categoryId: string, date: string, cursor: string | null, isDescending: boolean) =>
      `/chart/${categoryId}/section?date=${date}${cursor ? `&cursor=${cursor}` : ''}${isDescending ? '' : '&sortDirection=DESC'}`,
  },
  chat: {
    getAllChatrooms: (sortBy: ChatroomSortParam, cursor?: string | null) =>
      `/chatrooms?sortBy=${sortBy}${cursor ? `&cursor=${cursor}` : ''}`,
    getJoinedChatrooms: (cursor?: string | null) => `/users/me/chatrooms${cursor ? `?cursor=${cursor}` : ''}`,
    getHostedChatrooms: '/users/hosted-chatrooms',
    markAllAsRead: '/chatrooms/read-all',
    leaveMultipleChatrooms: '/chatrooms/leave',
    searchChatrooms: (keyword: string) => `/chatrooms/search?keyword=${keyword}`,
    addChatroom: '/chatrooms',
    getChatroom: (chatroomId: string) => `/chatrooms/${chatroomId}/edit`,
    editChatroom: (chatroomId: string) => `/chatrooms/${chatroomId}/edit`,
    leaveChatroom: (chatroomId: string) => `/chatrooms/${chatroomId}`,
    getChatroomCover: (chatroomId: string) => `/chatrooms/${chatroomId}`,
    enterChatroom: (chatroomId: string) => `/chatrooms/${chatroomId}/enter`,
    getChatroomLikeStatus: (chatroomId: string) => `/chatrooms/${chatroomId}/like`,
    toggleChatroomLike: (chatroomId: string) => `/chatrooms/${chatroomId}/like`,
    getChatroomMessages: (chatroomId: string, cursor?: number | null) =>
      `/chatrooms/${chatroomId}/messages${cursor ? `?cursor=${cursor}` : ''}`,
    getChatroomDetails: (chatroomId: string) => `/chatrooms/${chatroomId}/details`,
    getChatroomUserRole: (chatroomId: string) => `/chatrooms/${chatroomId}/role`,
    kickUser: (chatroomId: string, userId: number) => `/chatrooms/${chatroomId}/members/${userId}`,
    reportChatroomMember: (chatroomId: string, userId: number) => `/chatrooms/${chatroomId}/members/${userId}/reports`,
    getAllChatroomMembers: (chatroomId: string) => `/chatrooms/${chatroomId}/members/all`,
    searchChatroomMembers: (chatroomId: string, nickname: string) =>
      `/chatrooms/${chatroomId}/members/search${nickname && `?nickname=${nickname}`}`,
    delegateChatroomHost: (chatroomId: string) => `/chatrooms/${chatroomId}/host/delegate`,
  },
  notice: {
    getRecentNotice: (chatroomId: string) => `/chatrooms/${chatroomId}/notices`,
    getRecentNoticeList: (chatroomId: string) => `/chatrooms/${chatroomId}/notices/preview`,
    updateRecentNoticeStatus: (chatroomId: string) => `/chatrooms/${chatroomId}/notices`,
    getAllNoticeList: (chatroomId: string, cursor?: number | null) =>
      `/chatrooms/${chatroomId}/notices/all${cursor ? `?cursor=${cursor}` : ''}`,
    getNotice: (chatroomId: string, noticeId: string) => `/chatrooms/${chatroomId}/notices/${noticeId}`,
    addNotice: (chatroomId: string) => `/chatrooms/${chatroomId}/notices`,
    updateNotice: (chatroomId: string, noticeId: string) => `/chatrooms/${chatroomId}/notices/${noticeId}`,
    deleteNotice: (chatroomId: string, noticeId: number) => `/chatrooms/${chatroomId}/notices/${noticeId}`,
  },
  photo: {
    uploadChatroomPhoto: (chatroomId: string) => `/chatrooms/${chatroomId}/photos`,
    getRecentPhotoList: (chatroomId: string) => `/chatrooms/${chatroomId}/photos/preview`,
    getAllPhotoList: (chatroomId: string, cursor?: { date: string; id: number } | null) =>
      `/chatrooms/${chatroomId}/photos/all${cursor ? `?date=${cursor.date}&id=${cursor.id}` : ''}`,
    getPhotoDetail: (chatroomId: string, photoId: number) => `/chatrooms/${chatroomId}/photos/${photoId}`,
  },
  ranking: {
    getRecentRanking: (chatroomId: string) => `/chatrooms/${chatroomId}/rankings/preview`,
    getAllRankingList: (chatroomId: string, cursor?: number | null) =>
      `/chatrooms/${chatroomId}/rankings/all${cursor ? `?cursor=${cursor}` : ''}`,
  },
};
