export const endpoints = {
  auth: {
    signup: 'user/register',
    login: '/auth/login',
    logout: '/auth/logout',
    deleteUser: '/user/leave',
    checkNicknameDuplicate: '/user/exists/nickname',
    checkUsernameDuplicate: '/user/exists/username',
    refreshToken: '/auth/refresh',
  },
  email: {
    getEmail: '/user/email',
    sendEmail: '/email/send',
    verifyCode: '/email/verify',
  },
  total: {
    getMonthlyTotal: (date: string) => `/report/monthly/total?date=${date}`,
  },
  transaction: {
    getDailyDetails: (date: string) => `/report/daily/details?date=${date}`,
    addExpense: '/expense',
    getExpense: (id: string) => `/expense/${id}`,
    updateExpense: (id: string) => `/expense/${id}`,
    deleteExpense: (id: string) => `/expense/${id}`,
    addIncome: '/income',
    getIncome: (id: string) => `/income/${id}`,
    updateIncome: (id: string) => `/income/${id}`,
    deleteIncome: (id: string) => `/income/${id}`,
  },
  category: {
    updateActive: (id: string) => `/category/active/${id}`,
    getActive: (type: string) => `/category/active?type=${type}`,
    getDefaultExpense: '/category/expense/default',
    getCustomExpense: '/category/expense/custom',
    getDefaultIncome: '/category/income/default',
    getCustomIncome: '/category/income/custom',
    addExpense: '/category/expense',
    addIncome: '/category/income',
    getCategory: (id: string) => `/category/${id}`,
    updateCategory: (id: string) => `/category/${id}`,
    deleteCategory: (id: string) => `/category/${id}`,
  },
  report: {
    getYearlySummary: (date: string) => `/report/monthly/total?date=${date}`,
    getWeeklySummary: (date: string) => `/report/weekly/total?date=${date}`,
    getWeeklyDetails: (date: string, week: string) => `/report/weekly/details?date=${date}&week=${week}`,
  },
  chart: {
    getExpenseTotalAndSavings: (date: string) => `/chart/expense/total?date=${date}`,
    getIncomeTotalAndSavings: (date: string) => `/chart/income/total?date=${date}`,
  },
};
